name: jar obfuscator build

on:
  workflow_dispatch:

env:
  VERSION: "0.0.8-beta"

jobs:

  build:
    runs-on: windows-2019
    steps:
      - name: checkout the source
        uses: actions/checkout@v4
        with:
          path: jar-obfuscator

      - name: set up java 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'zulu'
          cache: maven

      - name: build core
        run: |
          .\package.bat
          mv .\target\jar-obfuscator-${{ env.VERSION }}-jar-with-dependencies.jar jar-obfuscator-${{ env.VERSION }}.jar
        working-directory: jar-obfuscator

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: jar-obfuscator
          path: |
            jar-obfuscator/jar-obfuscator-${{ env.VERSION }}.jar
